project:
  type: website
  output-dir: docs

website:
  title: "Walter Fenske"
  navbar:
    background: primary
    search: true
    left:
      - file: index.qmd
        text: "Home"
      - sidebar:mini_project
      - sidebar:mini_project2
      - file: StatModeling_Final_Project.qmd
        text: "MN Twins"
        
  sidebar:
    - id: mini_project
      title: "Mini Project 1"
      contents:
        - Map_Project.qmd
        - WisconsinVotes.qmd
        
    - id: mini_project2
      title: "Mini Project 2"
      contents: 
        - Simulation.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual




