project:
  type: website

website:
  title: "Walter Fenske"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Mini Project 1 - US Data"
        file: Map_Project.qmd
      - text: "Mini Project 1 - Wisconsin"
        file: WisconsinVotes.qmd
      - text: "About This Page"
        file: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


